# Book settings
title: "NiPreps"
author: Michael Joseph
copywright: 2020
logo: images/logo.png

# Execution settings
execute:
  execute_notebooks: auto

# HTML-specific settings
html:
  use_repository_button: true
  use_issues_button: false
  use_edit_page_button: false
  home_page_in_navbar: true

# Launch button settings
launch_buttons:
  notebook_interface: jupyterlab

repository:
  url: https://github.com/nipreps/nipreps-book
  path_to_book: docs
  branch: main
